### ISSUE TITLE
Do the authors describe how this software compares to other commonly-used packages?

### ISSUE THREAD

**Issue by volodymyrss** [grburgess/ronswanson#3]
But do the authors really describe how this software compares to other commonly-used packages?

https://github.com/openjournals/joss-reviews/issues/4969

**Comment by grburgess** [comment]
I wasn't really aware if there was something similar.

**Comment by volodymyrss** [comment]
According to the [guide](https://joss.readthedocs.io/en/latest/review_checklist.html):

>  A JOSS review is generally considered incomplete until the reviewer has checked off all of their checkboxes.

and there is this one:

> [ ] State of the field: Do the authors describe how this software compares to other commonly-used packages?

So technically I can not "generally" proceed until this is addressed.

On other other hand, in principle, useful software does not need to have such a section to remain useful. But in an ordinary paper one could require it. 

What do we do here, @dfm? 

Do we expect something like "to the best of  the author's knowledge this work is completely unprecedented"?

**Comment by dfm** [comment]
I generally expect that a JOSS paper should include some discussion of the software ecosystem context that the project exists within. If there truly aren't any similar projects, then it's fine to check that box, but I would generally expect there to be some comparable software that should be discussed for context. These comparisons certainly don't need to be in-depth, but should be included if at all possible!

**Comment by grburgess** [comment]
I could definitely add something about other spectral fitting software existing (xspec, isis, etc.) but wouldn't this be more related to the fitting package than the table building procedure? I'm unaware of anything other than one off solutions for this problem which is why the package was designed. But if there are others out there I'm happy to cite them.

**Comment by volodymyrss** [comment]
Ok then, we need a very brief insight from @grburgess on what are other at least remotely comparable solutions. 
Or a statement that there are none. 
I suppose in a narrow sense, just for `astromodels` - there are probably none.
But since people achieve something similar in other situations, it could be useful.

**Comment by grburgess** [comment]
@volodymyrss I do see this: https://github.com/mbursa/xspec-table-models which is a wrapper to generate an XSPEC fits file, but from an already existing simulation. Either way, I will write something up in a few moments.

**Comment by grburgess** [comment]
@volodymyrss I added a few sentences and refs in the statement of need section.
