### ISSUE TITLE
!simulation_build sim_build.yml  Traceback (most recent call last):   File "/opt/conda/bin/simulation_build", line 5, in <module>     from scripts.simulation_build import simulation_build ModuleNotFoundError: No module named 'scripts'

### ISSUE THREAD

**Issue by volodymyrss** [grburgess/ronswanson#5]
* ronswanson version: master
* Python version: 3.9
* Operating System: bullseye

### Description

```python
!simulation_build sim_build.yml

Traceback (most recent call last):
  File "/opt/conda/bin/simulation_build", line 5, in <module>
    from scripts.simulation_build import simulation_build
ModuleNotFoundError: No module named 'scripts'

```

**Comment by volodymyrss** [comment]
it's clear why, just because of the way it is, I thought maybe you want it to, but as you wish.

https://github.com/openjournals/joss-reviews/issues/4969

**Comment by grburgess** [comment]
whoops. Looks like that is not in the module list.

**Comment by grburgess** [comment]
Ahhh. I see the issue. Strange that this works with the develop install. Will fix in a moment.

**Comment by grburgess** [comment]
Ok, I think I have now fixed this and it is uploaded to pypi now @volodymyrss
